"""
Comprehensive NSE Stock Universe for Dynamic Screening.
Covers NIFTY 50 + Next 50 + Popular Midcaps + Smallcaps across ALL price ranges.
This gives the price filter meaningful coverage from ₹2 to ₹10,000+.
"""

# ~200 of the most liquid NSE stocks, organized by market cap tier
NSE_STOCKS = [
    # ========== NIFTY 50 (Large Cap) ==========
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "HCLTECH.NS", "TITAN.NS", "SUNPHARMA.NS", "TATAMOTORS.NS", "NTPC.NS",
    "WIPRO.NS", "ULTRACEMCO.NS", "ONGC.NS", "NESTLEIND.NS", "POWERGRID.NS",
    "M&M.NS", "JSWSTEEL.NS", "TATASTEEL.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "BAJAJFINSV.NS", "TECHM.NS", "HDFCLIFE.NS", "COALINDIA.NS", "GRASIM.NS",
    "DIVISLAB.NS", "DRREDDY.NS", "CIPLA.NS", "EICHERMOT.NS", "APOLLOHOSP.NS",
    "BPCL.NS", "TATACONSUM.NS", "SBILIFE.NS", "BRITANNIA.NS", "INDUSINDBK.NS",
    "HEROMOTOCO.NS", "BAJAJ-AUTO.NS", "HINDALCO.NS", "SHRIRAMFIN.NS", "LTIM.NS",

    # ========== NIFTY NEXT 50 (Large-Mid Cap) ==========
    "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "UNIONBANK.NS", "IOB.NS",
    "VEDL.NS", "GAIL.NS", "IOC.NS", "IRCTC.NS", "ZOMATO.NS",
    "NAUKRI.NS", "GODREJCP.NS", "SIEMENS.NS", "BOSCHLTD.NS", "HAVELLS.NS",
    "PIDILITIND.NS", "DLF.NS", "TRENT.NS", "INDIGO.NS", "BERGEPAINT.NS",
    "AMBUJACEM.NS", "ACC.NS", "TORNTPHARM.NS", "LUPIN.NS", "AUBANK.NS",
    "MCDOWELL-N.NS", "COLPAL.NS", "MARICO.NS", "DABUR.NS", "PIIND.NS",
    "ICICIPRULI.NS", "MUTHOOTFIN.NS", "LICI.NS", "TATAPOWER.NS", "ADANIGREEN.NS",

    # ========== MID CAP (₹200-₹2000 range) ==========
    "FEDERALBNK.NS", "IDFCFIRSTB.NS", "RBLBANK.NS", "MANAPPURAM.NS", "L&TFH.NS",
    "JUBLFOOD.NS", "PAGEIND.NS", "VOLTAS.NS", "AUROPHARMA.NS", "BIOCON.NS",
    "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS", "LTTS.NS", "TATAELXSI.NS",
    "CROMPTON.NS", "POLYCAB.NS", "ASTRAL.NS", "ATUL.NS", "DEEPAKNTR.NS",
    "NAVINFLUOR.NS", "SYNGENE.NS", "METROPOLIS.NS", "LALPATHLAB.NS", "MAXHEALTH.NS",
    "OBEROIRLTY.NS", "GODREJPROP.NS", "PRESTIGE.NS", "PHOENIXLTD.NS", "BRIGADE.NS",
    "BEL.NS", "HAL.NS", "BHEL.NS", "SAIL.NS", "NMDC.NS",
    "RECLTD.NS", "PFC.NS", "NHPC.NS", "SJVN.NS", "IRFC.NS",
    "CUMMINSIND.NS", "THERMAX.NS", "ABB.NS", "KAYNES.NS", "DIXON.NS",
    "DMART.NS", "TATACOMM.NS", "ZYDUSLIFE.NS", "ALKEM.NS", "IPCALAB.NS",

    # ========== SMALL CAP / LOW PRICE (₹5-₹200 range) ==========
    "IDEA.NS", "YESBANK.NS", "SUZLON.NS", "TTML.NS", "PAYTM.NS",
    "JPPOWER.NS", "RPOWER.NS", "GTLINFRA.NS", "JAIPRAKASH.NS", "JPASSOCIAT.NS",
    "IREDA.NS", "HFCL.NS", "NBCC.NS", "HUDCO.NS", "RVNL.NS",
    "NATIONALUM.NS", "HINDZINC.NS", "HINDCOPPER.NS", "GMRAIRPORT.NS", "ADANIPOWER.NS",
    "DELTACORP.NS", "BANDHANBNK.NS", "INDIANB.NS", "CENTRALBK.NS", "MAHABANK.NS",
    "UCO.NS", "BANKINDIA.NS", "PSB.NS", "NIACL.NS", "GICRE.NS",
    "IEX.NS", "CDSL.NS", "BSE.NS", "MCX.NS", "CAMS.NS",
    "TATACHEM.NS", "CHAMBAL.NS", "GNFC.NS", "FACT.NS", "RCF.NS",
    "NFL.NS", "MRPL.NS", "PETRONET.NS", "GUJGASLTD.NS", "MGL.NS",

    # ========== POPULAR THEMATIC (Defence, Railway, PSU) ==========
    "MAZAGON.NS", "GRSE.NS", "COCHINSHIP.NS", "GARDENREACH.NS",
    "RITES.NS", "RAILTEL.NS", "TIINDIA.NS",
    "SOLARINDS.NS", "CLEAN.NS", "TATATECH.NS", "JSWENERGY.NS",
]

def get_universe():
    """Return the full NSE stock universe list."""
    return list(set(NSE_STOCKS))  # deduplicate just in case
